# Generated by Django 4.2.16 on 2026-06-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_driverprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='firebase_uid',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
