# Generated by Django 4.2.16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0004_trip_firebase_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='cycle_used_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='ruleset',
            field=models.CharField(blank=True, default='70-hour/8-day', max_length=50),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
