# Generated by Django 4.2.16 on 2026-06-22 12:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_driverprofile_extended'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=255)),
                ('pickup', models.CharField(blank=True, default='', max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('ruleset', models.CharField(default='70-hour/8-day', max_length=50)),
                ('cycle_used_at_start', models.FloatField(default=0.0)),
                ('total_miles', models.FloatField(blank=True, null=True)),
                ('estimated_drive_hours', models.FloatField(blank=True, null=True)),
                ('stops', models.JSONField(blank=True, default=list)),
                ('daily_logs', models.JSONField(blank=True, default=list)),
                ('violation_risk', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_records', to='api.driverprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
