# Generated by Django 4.2.16 on 2026-06-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_triprecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='violation_risk',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
